[project]
name = "azevedo-wolff-replication"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cvxpy>=1.7.5",
    "matplotlib>=3.10.7",
    "moralhazard",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "pyyaml>=6.0.3",
]

[tool.uv.sources]
moralhazard = { git = "https://github.com/eduardomazevedo/moralhazard.git", rev = "96659e080ed6bbd2e8c63d14746114f0362da52f" }
